/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flashablezipcreator;

/**
 *
 * @author Nikhil
 */
public class AddDescriptionUI extends javax.swing.JFrame {

    /**
     * Creates new form AddDescriptionUI
     */
    public AddDescriptionUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ADPanel = new javax.swing.JPanel();
        AD_headingPanel = new javax.swing.JPanel();
        lblADHeading = new javax.swing.JLabel();
        addDescriptionScrollPane = new javax.swing.JScrollPane();
        textAreaAddDescription = new javax.swing.JTextArea();
        btnDoneDescription = new javax.swing.JButton();
        btnResetDescription = new javax.swing.JButton();
        btnCancelDescription = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AD_headingPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblADHeading.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblADHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblADHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblADHeading.setText("Add Description");

        javax.swing.GroupLayout AD_headingPanelLayout = new javax.swing.GroupLayout(AD_headingPanel);
        AD_headingPanel.setLayout(AD_headingPanelLayout);
        AD_headingPanelLayout.setHorizontalGroup(
            AD_headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AD_headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblADHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        AD_headingPanelLayout.setVerticalGroup(
            AD_headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AD_headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblADHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        textAreaAddDescription.setColumns(20);
        textAreaAddDescription.setRows(5);
        addDescriptionScrollPane.setViewportView(textAreaAddDescription);

        btnDoneDescription.setText("Done");
        btnDoneDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneDescriptionActionPerformed(evt);
            }
        });

        btnResetDescription.setText("Reset");
        btnResetDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetDescriptionActionPerformed(evt);
            }
        });

        btnCancelDescription.setText("Cancel");
        btnCancelDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelDescriptionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ADPanelLayout = new javax.swing.GroupLayout(ADPanel);
        ADPanel.setLayout(ADPanelLayout);
        ADPanelLayout.setHorizontalGroup(
            ADPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ADPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(AD_headingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ADPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(addDescriptionScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ADPanelLayout.createSequentialGroup()
                            .addComponent(btnDoneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnResetDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnCancelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ADPanelLayout.setVerticalGroup(
            ADPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ADPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AD_headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addDescriptionScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ADPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDoneDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ADPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ADPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoneDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoneDescriptionActionPerformed

    private void btnResetDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetDescriptionActionPerformed

    private void btnCancelDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelDescriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddDescriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddDescriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddDescriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddDescriptionUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddDescriptionUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ADPanel;
    private javax.swing.JPanel AD_headingPanel;
    private javax.swing.JScrollPane addDescriptionScrollPane;
    private javax.swing.JButton btnCancelDescription;
    private javax.swing.JButton btnDoneDescription;
    private javax.swing.JButton btnResetDescription;
    private javax.swing.JLabel lblADHeading;
    private javax.swing.JTextArea textAreaAddDescription;
    // End of variables declaration//GEN-END:variables
}
