/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flashablezipcreator;

/**
 *
 * @author Nikhil
 */
public class changeDPIUI extends javax.swing.JFrame {

    /**
     * Creates new form changeDPIUI
     */
    public changeDPIUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeDpiPanel = new javax.swing.JPanel();
        ChangeDpi_headingPanel = new javax.swing.JPanel();
        lblChangeDpiHeading = new javax.swing.JLabel();
        changeDpiScrollPane = new javax.swing.JScrollPane();
        changeDpiList = new javax.swing.JList();
        btnAddChangeDpi = new javax.swing.JButton();
        btnRemoveChangeDpi = new javax.swing.JButton();
        btnResetChangeDpi = new javax.swing.JButton();
        btnDoneChangeDpi = new javax.swing.JButton();
        textFieldChangeDpi = new javax.swing.JTextField();
        lbl_changeDpiValue = new javax.swing.JLabel();
        lbl_changeDpiEg = new javax.swing.JLabel();
        lbl_changeDpiHeading = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ChangeDpi_headingPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblChangeDpiHeading.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblChangeDpiHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblChangeDpiHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChangeDpiHeading.setText("Custom Dpi");

        javax.swing.GroupLayout ChangeDpi_headingPanelLayout = new javax.swing.GroupLayout(ChangeDpi_headingPanel);
        ChangeDpi_headingPanel.setLayout(ChangeDpi_headingPanelLayout);
        ChangeDpi_headingPanelLayout.setHorizontalGroup(
            ChangeDpi_headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangeDpi_headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChangeDpiHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ChangeDpi_headingPanelLayout.setVerticalGroup(
            ChangeDpi_headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChangeDpi_headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblChangeDpiHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        changeDpiList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        changeDpiList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        changeDpiList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                changeDpiListValueChanged(evt);
            }
        });
        changeDpiScrollPane.setViewportView(changeDpiList);

        btnAddChangeDpi.setText("Add");
        btnAddChangeDpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddChangeDpiActionPerformed(evt);
            }
        });

        btnRemoveChangeDpi.setText("Remove");
        btnRemoveChangeDpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveChangeDpiActionPerformed(evt);
            }
        });

        btnResetChangeDpi.setText("Reset");
        btnResetChangeDpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetChangeDpiActionPerformed(evt);
            }
        });

        btnDoneChangeDpi.setText("Done!");
        btnDoneChangeDpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneChangeDpiActionPerformed(evt);
            }
        });

        textFieldChangeDpi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbl_changeDpiValue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_changeDpiValue.setText("Enter Dpi Value : ");

        lbl_changeDpiEg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_changeDpiEg.setText("(eg. 210)");

        lbl_changeDpiHeading.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_changeDpiHeading.setText("Enter all the Dpi values that you would like to change.");

        javax.swing.GroupLayout changeDpiPanelLayout = new javax.swing.GroupLayout(changeDpiPanel);
        changeDpiPanel.setLayout(changeDpiPanelLayout);
        changeDpiPanelLayout.setHorizontalGroup(
            changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeDpiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ChangeDpi_headingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_changeDpiHeading)
                        .addGroup(changeDpiPanelLayout.createSequentialGroup()
                            .addComponent(lbl_changeDpiValue)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(textFieldChangeDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl_changeDpiEg))
                        .addGroup(changeDpiPanelLayout.createSequentialGroup()
                            .addComponent(changeDpiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRemoveChangeDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDoneChangeDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnResetChangeDpi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnAddChangeDpi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changeDpiPanelLayout.setVerticalGroup(
            changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeDpiPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeDpiPanelLayout.createSequentialGroup()
                        .addComponent(ChangeDpi_headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_changeDpiHeading)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldChangeDpi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_changeDpiValue)
                            .addComponent(lbl_changeDpiEg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btnResetChangeDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDoneChangeDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changeDpiPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(changeDpiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(changeDpiPanelLayout.createSequentialGroup()
                                .addComponent(btnAddChangeDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRemoveChangeDpi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))
                            .addComponent(changeDpiScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changeDpiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changeDpiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changeDpiListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_changeDpiListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_changeDpiListValueChanged

    private void btnAddChangeDpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddChangeDpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddChangeDpiActionPerformed

    private void btnRemoveChangeDpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveChangeDpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveChangeDpiActionPerformed

    private void btnResetChangeDpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetChangeDpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetChangeDpiActionPerformed

    private void btnDoneChangeDpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneChangeDpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoneChangeDpiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeDPIUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeDPIUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeDPIUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeDPIUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeDPIUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ChangeDpi_headingPanel;
    private javax.swing.JButton btnAddChangeDpi;
    private javax.swing.JButton btnDoneChangeDpi;
    private javax.swing.JButton btnRemoveChangeDpi;
    private javax.swing.JButton btnResetChangeDpi;
    private javax.swing.JList changeDpiList;
    private javax.swing.JPanel changeDpiPanel;
    private javax.swing.JScrollPane changeDpiScrollPane;
    private javax.swing.JLabel lblChangeDpiHeading;
    private javax.swing.JLabel lbl_changeDpiEg;
    private javax.swing.JLabel lbl_changeDpiHeading;
    private javax.swing.JLabel lbl_changeDpiValue;
    private javax.swing.JTextField textFieldChangeDpi;
    // End of variables declaration//GEN-END:variables
}
