/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flashablezipcreator;

/**
 *
 * @author Nikhil
 */
public class CreateZipUI extends javax.swing.JFrame {

    /**
     * Creates new form CreateZipUI
     */
    public CreateZipUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CZPanel = new javax.swing.JPanel();
        CZ_headingPanel9 = new javax.swing.JPanel();
        lblCZHeading9 = new javax.swing.JLabel();
        tabbedPaneCZ = new javax.swing.JTabbedPane();
        runPanel = new javax.swing.JPanel();
        runScrollPaneCZ = new javax.swing.JScrollPane();
        runTextAreaCZ = new javax.swing.JTextArea();
        progressCZ = new javax.swing.JProgressBar();
        debugPanel = new javax.swing.JPanel();
        debugScrollPaneCZ = new javax.swing.JScrollPane();
        debugTextAreaCZ = new javax.swing.JTextArea();
        btnClearLogCZ = new javax.swing.JButton();
        btnSaveLogCZ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CZ_headingPanel9.setBackground(new java.awt.Color(0, 0, 0));

        lblCZHeading9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblCZHeading9.setForeground(new java.awt.Color(255, 255, 255));
        lblCZHeading9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCZHeading9.setText("Creating Flashable ZIP");

        javax.swing.GroupLayout CZ_headingPanel9Layout = new javax.swing.GroupLayout(CZ_headingPanel9);
        CZ_headingPanel9.setLayout(CZ_headingPanel9Layout);
        CZ_headingPanel9Layout.setHorizontalGroup(
            CZ_headingPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CZ_headingPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCZHeading9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CZ_headingPanel9Layout.setVerticalGroup(
            CZ_headingPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CZ_headingPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCZHeading9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        runTextAreaCZ.setColumns(20);
        runTextAreaCZ.setRows(5);
        runScrollPaneCZ.setViewportView(runTextAreaCZ);

        javax.swing.GroupLayout runPanelLayout = new javax.swing.GroupLayout(runPanel);
        runPanel.setLayout(runPanelLayout);
        runPanelLayout.setHorizontalGroup(
            runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(runScrollPaneCZ, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
            .addComponent(progressCZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        runPanelLayout.setVerticalGroup(
            runPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(runPanelLayout.createSequentialGroup()
                .addComponent(runScrollPaneCZ, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressCZ, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        tabbedPaneCZ.addTab("Running", runPanel);

        debugTextAreaCZ.setColumns(20);
        debugTextAreaCZ.setRows(5);
        debugScrollPaneCZ.setViewportView(debugTextAreaCZ);

        btnClearLogCZ.setText("Clear All");

        btnSaveLogCZ.setText("Save Logs");

        javax.swing.GroupLayout debugPanelLayout = new javax.swing.GroupLayout(debugPanel);
        debugPanel.setLayout(debugPanelLayout);
        debugPanelLayout.setHorizontalGroup(
            debugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(debugScrollPaneCZ)
            .addGroup(debugPanelLayout.createSequentialGroup()
                .addContainerGap(276, Short.MAX_VALUE)
                .addComponent(btnClearLogCZ, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSaveLogCZ))
        );
        debugPanelLayout.setVerticalGroup(
            debugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, debugPanelLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(debugPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveLogCZ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClearLogCZ, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(debugScrollPaneCZ, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        tabbedPaneCZ.addTab("Debug", debugPanel);

        javax.swing.GroupLayout CZPanelLayout = new javax.swing.GroupLayout(CZPanel);
        CZPanel.setLayout(CZPanelLayout);
        CZPanelLayout.setHorizontalGroup(
            CZPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CZPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CZPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabbedPaneCZ, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CZ_headingPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        CZPanelLayout.setVerticalGroup(
            CZPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CZPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CZ_headingPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPaneCZ, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CZPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CZPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateZipUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateZipUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateZipUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateZipUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateZipUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CZPanel;
    private javax.swing.JPanel CZ_Panel;
    private javax.swing.JPanel CZ_Panel1;
    private javax.swing.JPanel CZ_Panel2;
    private javax.swing.JPanel CZ_Panel3;
    private javax.swing.JPanel CZ_Panel4;
    private javax.swing.JPanel CZ_Panel5;
    private javax.swing.JPanel CZ_Panel6;
    private javax.swing.JPanel CZ_Panel7;
    private javax.swing.JPanel CZ_Panel8;
    private javax.swing.JPanel CZ_headingPanel;
    private javax.swing.JPanel CZ_headingPanel1;
    private javax.swing.JPanel CZ_headingPanel2;
    private javax.swing.JPanel CZ_headingPanel3;
    private javax.swing.JPanel CZ_headingPanel4;
    private javax.swing.JPanel CZ_headingPanel5;
    private javax.swing.JPanel CZ_headingPanel6;
    private javax.swing.JPanel CZ_headingPanel7;
    private javax.swing.JPanel CZ_headingPanel8;
    private javax.swing.JPanel CZ_headingPanel9;
    private javax.swing.JButton btnClearLogCZ;
    private javax.swing.JButton btnSaveLogCZ;
    private javax.swing.JPanel debugPanel;
    private javax.swing.JScrollPane debugScrollPaneCZ;
    private javax.swing.JTextArea debugTextAreaCZ;
    private javax.swing.JLabel lblCZHeading;
    private javax.swing.JLabel lblCZHeading1;
    private javax.swing.JLabel lblCZHeading2;
    private javax.swing.JLabel lblCZHeading3;
    private javax.swing.JLabel lblCZHeading4;
    private javax.swing.JLabel lblCZHeading5;
    private javax.swing.JLabel lblCZHeading6;
    private javax.swing.JLabel lblCZHeading7;
    private javax.swing.JLabel lblCZHeading8;
    private javax.swing.JLabel lblCZHeading9;
    private javax.swing.JProgressBar progressCZ;
    private javax.swing.JPanel runPanel;
    private javax.swing.JScrollPane runScrollPaneCZ;
    private javax.swing.JTextArea runTextAreaCZ;
    private javax.swing.JTabbedPane tabbedPaneCZ;
    // End of variables declaration//GEN-END:variables
}
