/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flashablezipcreator;

/**
 *
 * @author Nikhil
 */
public class ImportZipUI extends javax.swing.JFrame {

    /**
     * Creates new form ImportZipUI
     */
    public ImportZipUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importZipPanel = new javax.swing.JPanel();
        IZheader_panel = new javax.swing.JPanel();
        lblIZheader = new javax.swing.JLabel();
        lblSelectZip = new javax.swing.JLabel();
        textFieldSelectZip = new javax.swing.JTextField();
        btnBrowseZip = new javax.swing.JButton();
        progressImportZip = new javax.swing.JProgressBar();
        lblProgress = new javax.swing.JLabel();
        scrollPaneImportZip = new javax.swing.JScrollPane();
        textAreaImportZipLog = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IZheader_panel.setBackground(new java.awt.Color(0, 0, 0));

        lblIZheader.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        lblIZheader.setForeground(new java.awt.Color(255, 255, 255));
        lblIZheader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIZheader.setText("Import Previously Created Zip");

        javax.swing.GroupLayout IZheader_panelLayout = new javax.swing.GroupLayout(IZheader_panel);
        IZheader_panel.setLayout(IZheader_panelLayout);
        IZheader_panelLayout.setHorizontalGroup(
            IZheader_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IZheader_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIZheader, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                .addContainerGap())
        );
        IZheader_panelLayout.setVerticalGroup(
            IZheader_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IZheader_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblIZheader, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblSelectZip.setText("Select Zip : ");

        textFieldSelectZip.setEditable(false);
        textFieldSelectZip.setText("Click Browse To Select Zip File...");

        btnBrowseZip.setText("Browse..");
        btnBrowseZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseZipActionPerformed(evt);
            }
        });

        lblProgress.setText("Progress : ");

        textAreaImportZipLog.setColumns(20);
        textAreaImportZipLog.setRows(5);
        scrollPaneImportZip.setViewportView(textAreaImportZipLog);

        javax.swing.GroupLayout importZipPanelLayout = new javax.swing.GroupLayout(importZipPanel);
        importZipPanel.setLayout(importZipPanelLayout);
        importZipPanelLayout.setHorizontalGroup(
            importZipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importZipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(importZipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(IZheader_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(importZipPanelLayout.createSequentialGroup()
                        .addComponent(lblSelectZip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldSelectZip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBrowseZip))
                    .addGroup(importZipPanelLayout.createSequentialGroup()
                        .addComponent(lblProgress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(progressImportZip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(scrollPaneImportZip))
                .addContainerGap())
        );
        importZipPanelLayout.setVerticalGroup(
            importZipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importZipPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IZheader_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(importZipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectZip)
                    .addComponent(textFieldSelectZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseZip))
                .addGap(17, 17, 17)
                .addGroup(importZipPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(importZipPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblProgress))
                    .addComponent(progressImportZip, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrollPaneImportZip, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(importZipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(importZipPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseZipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImportZipUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImportZipUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImportZipUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImportZipUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImportZipUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IZheader_panel;
    private javax.swing.JButton btnBrowseZip;
    private javax.swing.JPanel importZipPanel;
    private javax.swing.JLabel lblIZheader;
    private javax.swing.JLabel lblProgress;
    private javax.swing.JLabel lblSelectZip;
    private javax.swing.JProgressBar progressImportZip;
    private javax.swing.JScrollPane scrollPaneImportZip;
    private javax.swing.JTextArea textAreaImportZipLog;
    private javax.swing.JTextField textFieldSelectZip;
    // End of variables declaration//GEN-END:variables
}
