/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package flashablezipcreator;

/**
 *
 * @author Nikhil
 */
public class OtherPreferencesUI extends javax.swing.JFrame {

    /**
     * Creates new form OtherPreferencesUI
     */
    public OtherPreferencesUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OPPanel = new javax.swing.JPanel();
        OP_headingPanel = new javax.swing.JPanel();
        lblOPHeading = new javax.swing.JLabel();
        dalvikCacheCheckBox = new javax.swing.JCheckBox();
        btnBrowseBuildProp = new javax.swing.JButton();
        btnBrowseHostsFile = new javax.swing.JButton();
        ScrollPaneOP = new javax.swing.JScrollPane();
        TextAreaOP = new javax.swing.JTextArea();
        buildPropTextField = new javax.swing.JTextField();
        hostsFileTextField = new javax.swing.JTextField();
        modifyOptionsPanel = new javax.swing.JPanel();
        btnModifyAromaUpdaterScript = new javax.swing.JButton();
        btnModifyAromaConfig = new javax.swing.JButton();
        btnModifyBuildProp = new javax.swing.JButton();
        btnModifyHostsFile = new javax.swing.JButton();
        btnModifyNormalUpdaterScript = new javax.swing.JButton();
        saveOptionsPanel = new javax.swing.JPanel();
        btnSaveModify = new javax.swing.JButton();
        btnDoneModify = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OP_headingPanel.setBackground(new java.awt.Color(0, 0, 0));

        lblOPHeading.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        lblOPHeading.setForeground(new java.awt.Color(255, 255, 255));
        lblOPHeading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOPHeading.setText("Other Preferences");

        javax.swing.GroupLayout OP_headingPanelLayout = new javax.swing.GroupLayout(OP_headingPanel);
        OP_headingPanel.setLayout(OP_headingPanelLayout);
        OP_headingPanelLayout.setHorizontalGroup(
            OP_headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP_headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOPHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        OP_headingPanelLayout.setVerticalGroup(
            OP_headingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OP_headingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOPHeading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        dalvikCacheCheckBox.setText("Clear Dalvik Cache After Installation By Default");
        dalvikCacheCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dalvikCacheCheckBoxActionPerformed(evt);
            }
        });

        btnBrowseBuildProp.setText("browse");
        btnBrowseBuildProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseBuildPropActionPerformed(evt);
            }
        });

        btnBrowseHostsFile.setText("browse");
        btnBrowseHostsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseHostsFileActionPerformed(evt);
            }
        });

        TextAreaOP.setColumns(20);
        TextAreaOP.setRows(5);
        ScrollPaneOP.setViewportView(TextAreaOP);

        buildPropTextField.setText("Click here to Import Build.prop...");

        hostsFileTextField.setText("Click here to Import Hosts File...");

        modifyOptionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        modifyOptionsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnModifyAromaUpdaterScript.setText("Modify Aroma updater-script");
        btnModifyAromaUpdaterScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyAromaUpdaterScriptActionPerformed(evt);
            }
        });

        btnModifyAromaConfig.setText("Modify aroma-config");
        btnModifyAromaConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyAromaConfigActionPerformed(evt);
            }
        });

        btnModifyBuildProp.setText("Modify Build.prop");
        btnModifyBuildProp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyBuildPropActionPerformed(evt);
            }
        });

        btnModifyHostsFile.setText("Modify Hosts File");
        btnModifyHostsFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyHostsFileActionPerformed(evt);
            }
        });

        btnModifyNormalUpdaterScript.setText("Modify Normal updater-script");
        btnModifyNormalUpdaterScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyNormalUpdaterScriptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout modifyOptionsPanelLayout = new javax.swing.GroupLayout(modifyOptionsPanel);
        modifyOptionsPanel.setLayout(modifyOptionsPanelLayout);
        modifyOptionsPanelLayout.setHorizontalGroup(
            modifyOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, modifyOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modifyOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModifyAromaConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifyBuildProp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifyHostsFile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, modifyOptionsPanelLayout.createSequentialGroup()
                        .addGroup(modifyOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModifyAromaUpdaterScript)
                            .addComponent(btnModifyNormalUpdaterScript))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        modifyOptionsPanelLayout.setVerticalGroup(
            modifyOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modifyOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnModifyAromaUpdaterScript, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnModifyNormalUpdaterScript, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifyAromaConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifyBuildProp, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModifyHostsFile, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        saveOptionsPanel.setBackground(new java.awt.Color(255, 255, 255));
        saveOptionsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSaveModify.setText("Save");
        btnSaveModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveModifyActionPerformed(evt);
            }
        });

        btnDoneModify.setText("Done!");
        btnDoneModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneModifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveOptionsPanelLayout = new javax.swing.GroupLayout(saveOptionsPanel);
        saveOptionsPanel.setLayout(saveOptionsPanelLayout);
        saveOptionsPanelLayout.setHorizontalGroup(
            saveOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saveOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaveModify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDoneModify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        saveOptionsPanelLayout.setVerticalGroup(
            saveOptionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveOptionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSaveModify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDoneModify, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout OPPanelLayout = new javax.swing.GroupLayout(OPPanel);
        OPPanel.setLayout(OPPanelLayout);
        OPPanelLayout.setHorizontalGroup(
            OPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OPPanelLayout.createSequentialGroup()
                .addGroup(OPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(OPPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(OP_headingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OPPanelLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addGroup(OPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OPPanelLayout.createSequentialGroup()
                                .addComponent(hostsFileTextField)
                                .addGap(10, 10, 10)
                                .addComponent(btnBrowseHostsFile))
                            .addGroup(OPPanelLayout.createSequentialGroup()
                                .addComponent(buildPropTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBrowseBuildProp))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, OPPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ScrollPaneOP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(OPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(modifyOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveOptionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(OPPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dalvikCacheCheckBox)))
                .addContainerGap())
        );
        OPPanelLayout.setVerticalGroup(
            OPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OPPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OP_headingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowseBuildProp)
                    .addComponent(buildPropTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(OPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowseHostsFile)
                    .addComponent(hostsFileTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(OPPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(OPPanelLayout.createSequentialGroup()
                        .addComponent(modifyOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saveOptionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ScrollPaneOP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dalvikCacheCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OPPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseBuildPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseBuildPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseBuildPropActionPerformed

    private void btnBrowseHostsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseHostsFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBrowseHostsFileActionPerformed

    private void btnModifyAromaUpdaterScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyAromaUpdaterScriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyAromaUpdaterScriptActionPerformed

    private void btnModifyAromaConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyAromaConfigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyAromaConfigActionPerformed

    private void btnModifyBuildPropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyBuildPropActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyBuildPropActionPerformed

    private void btnModifyHostsFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyHostsFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyHostsFileActionPerformed

    private void btnSaveModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveModifyActionPerformed

    private void btnDoneModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneModifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoneModifyActionPerformed

    private void dalvikCacheCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dalvikCacheCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dalvikCacheCheckBoxActionPerformed

    private void btnModifyNormalUpdaterScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyNormalUpdaterScriptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifyNormalUpdaterScriptActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherPreferencesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherPreferencesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherPreferencesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherPreferencesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtherPreferencesUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OPPanel;
    private javax.swing.JPanel OP_headingPanel;
    private javax.swing.JScrollPane ScrollPaneOP;
    private javax.swing.JTextArea TextAreaOP;
    private javax.swing.JButton btnBrowseBuildProp;
    private javax.swing.JButton btnBrowseHostsFile;
    private javax.swing.JButton btnDoneModify;
    private javax.swing.JButton btnModifyAromaConfig;
    private javax.swing.JButton btnModifyAromaUpdaterScript;
    private javax.swing.JButton btnModifyBuildProp;
    private javax.swing.JButton btnModifyHostsFile;
    private javax.swing.JButton btnModifyNormalUpdaterScript;
    private javax.swing.JButton btnSaveModify;
    private javax.swing.JTextField buildPropTextField;
    private javax.swing.JCheckBox dalvikCacheCheckBox;
    private javax.swing.JTextField hostsFileTextField;
    private javax.swing.JLabel lblOPHeading;
    private javax.swing.JPanel modifyOptionsPanel;
    private javax.swing.JPanel saveOptionsPanel;
    // End of variables declaration//GEN-END:variables
}
